module.exports = {
  PEER_JOIN: 'PEER_JOIN',
  PEER_LEAVE: 'PEER_LEAVE',
  PEER_UPDATE: 'PEER_UPDATE',
  MESSAGE: 'MESSAGE',
  SUBSCRIBED: 'SUBSCRIBED',
  UNSUBSCRIBED: 'UNSUBSCRIBED',
  PUBLISHED: 'PUBLISHED',
  ERROR: 'ERROR',
}
